### ISSUE TITLE
Bug when executing ya2ro

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/ya2ro#39] opened 2022-03-04 16:36 UTC
Input command: `ya2ro -i templates/sample_links.yaml`

Result:

```
WARNING: 'summary' is not defined. Add it to be eligible for beeing an EELISA project.
Traceback (most recent call last):
  File "/home/dgarijo/Documents/GitHub/ya2ro/env_3.9/bin/ya2ro", line 33, in <module>
    sys.exit(load_entry_point('ya2ro', 'console_scripts', 'ya2ro')())
  File "/home/dgarijo/Documents/GitHub/ya2ro/src/ya2ro/ya2ro.py", line 74, in main
    process_yaml(args.input)
  File "/home/dgarijo/Documents/GitHub/ya2ro/src/ya2ro/ya2ro.py", line 117, in process_yaml
    rhtml.load_data(data)
  File "/home/dgarijo/Documents/GitHub/ya2ro/src/ya2ro/ro_html.py", line 61, in load_data
    self.func_attr_init[attr_name](attr_val)
  File "/home/dgarijo/Documents/GitHub/ya2ro/src/ya2ro/ro_html.py", line 389, in init_software
    software_cards_scc += card_html_view(s.metadata,embedded=True)
  File "/home/dgarijo/Documents/GitHub/ya2ro/env_3.9/lib/python3.9/site-packages/scc/commands/software_catalog_portal/card.py", line 71, in html_view
    {md.recently_updated()}
  File "/home/dgarijo/Documents/GitHub/ya2ro/env_3.9/lib/python3.9/site-packages/scc/commands/software_catalog_portal/metadata.py", line 186, in recently_updated
    delta = self.last_update_days()
  File "/home/dgarijo/Documents/GitHub/ya2ro/env_3.9/lib/python3.9/site-packages/scc/commands/software_catalog_portal/metadata.py", line 293, in last_update_days
    date_of_extraction_str = safe_dic(safe_dic(safe_dic(self.md,'stargazersCount'),'excerpt'),'date')[:-4]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by dgarijo** [comment] 2022-03-04 16:47
It worked with the `ns` option, which makes me think there is maybe an integration problem with scc

**Comment by PavelAntonia** [comment] 2022-03-12 18:13
This bug seems to be fixed in the later versions of SCC. I can not replicate the bug.
I'll close this issue for now.

**Closed by PavelAntonia** 2022-03-12 18:13 UTC
Labels: bug

**Comment by dgarijo** [comment] 2022-03-12 18:38
I ran this with the latest code in the repository. No new commits have been pushed since, so the bug still happens.
If you claim it is fixed, then I think you should post what can I do to avoid running into it again.

**Comment by dakixr** [comment] 2022-03-12 20:17
Hi! Antonia ask me about this bug. 

This may be caused by your current env for having an older version of SOMEF.
As you well know they changed some field names: in this case, the one that is causing trouble is 'stargazersCount' which was previously named 'stargazers_count'.

Hope that this helps.

**Comment by dgarijo** [comment] 2022-03-12 20:35
Then ya2ro and scc should have releases specifying the version of somef needed to avoid these kinds of issues :)
